# Generated by Django 3.1.7 on 2021-03-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloge_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postyoz',
            name='image',
            field=models.CharField(default='https://media-exp1.licdn.com/dms/image/C561BAQGQ6dIcBhfqaw/company-background_10000/0/1526873579149?e=2159024400&v=beta&t=_2aB5pycriIFXMGz_KbKNumpcy28CgpnzC5cq-Iw81w', max_length=400),
        ),
    ]
