# Generated by Django 3.1.7 on 2021-03-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloge_app', '0002_postyoz_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postyoz',
            name='description',
            field=models.TextField(blank=True, max_length=160),
        ),
    ]
