# Generated by Django 3.1.7 on 2021-03-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloge_app', '0004_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
